# flask-bp sample configuration file
# I used yaml as configuration file however you can use which ever you want
# this file contains some parameters used for the database configuration
# to learn more about yaml files see @ http://yaml.org/

# configuration for the database
database:
  # specify the address of the database e.g 192.168.100.12
  host: localhost
  # specify the port used for the database e.g for postgres default port is 5432
  port: 5432
  # specify the user name for the database e.g postgres
  user_name: flask-bp
  # specify the password for the database
  password: password
  # specify the database name here
  database_name: flask-bp

# development server configuration
dev-server:
  # specify the host address e.g default is 127.0.0.1 or localhost
  host: 127.0.0.1
  # specify the port for the server e.g default port is 5000
  port: 5000